server:
  port: 8038

jwt:
  secret: ${JWT_SECRET}
  expiration: 10800000

spring:
  application:
    name: smart-logistics-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_logistics
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-migration-naming: true
    default-schema: public

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG