
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_logistics
    username: postgres
    password: Viateur@123

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: smart-logistics-backend


